### ISSUE TITLE
Want Image Search result in Cards

### ISSUE THREAD

**Issue by ajeetjaiswal02** [ajeetjaiswal02/SImple_React-_mage_Search_Hacktoberfest2021#2]
Image search result after API call comes in mesh format want to put in card Format I want help in that kind a busy right now

**Comment by MuditWadhwa** [comment]
Hi, I would like to contribute to this repository by solving this issue. Please assign this issue to me.

**Comment by ajeetjaiswal02** [comment]
I have  Merge an update from another user but still, you can do  improvement in it

**Comment by Mark-42-max** [comment]
Hello! I would like to work on this issue. Would you like to assign the issue to me?

**Comment by ajeetjaiswal02** [comment]
Thanks iShubhamRana for solving this issue 🥇
